---
- name: Deploy PostgreSQL on Event Catalogue hosts
  hosts: event_catalogue
  become: yes

  tasks:
    - name: Install packages
      dnf: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server

    - name: Install Python packages
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary

    - name: Check if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: Initialize PostgreSQL
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists
 
    - name: Start and enable services
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

    - name: Set password for Linux user
      ansible.builtin.user:
        name: postgres
        password: "{{ postgres_hashed_password }}"
  
    # Is it needed ?
    - name: Set password for postgres user
      become: yes
      become_method: su
      become_user: postgres
      vars:
        ansible_become_password: example
      postgresql_user:
        db: postgres
        name: postgres
        password: example
        # login_user: postgres
        login_password: "{{ psql_password }}" 

    - name: Add configuration to pg_hba.conf
      blockinfile:
        dest: /var/lib/pgsql/data/pg_hba.conf
        insertafter: 
          "# TYPE  DATABASE        USER            ADDRESS                 METHOD"
        block: |
          local   all             all             	                   md5
          host    all             all             0.0.0.0/0                md5
          host    replication     postgres        0.0.0.0/0                password
      register: result_pg_hba

    - name: Add new configuration to postgresql.conf
      blockinfile:
        dest: /var/lib/pgsql/data/postgresql.conf
        block: |
          listen_addresses = '*'
      register: result_postgresql_conf

    - name: Restart postgres if configs changed
      service: 
        name: postgresql 
        state: restarted
      when: result_pg_hba.changed or result_postgresql_conf.changed

    - name: Ensure Event Catalogue database is created
      postgresql_db: 
        name: "{{ event_catalogue_db_name }}"
        login_password: "{{ psql_password }}"

    - name: Upload SQL script file
      copy:
        src: files/schema.sql
        dest: /var/tmp/schema.sql

    - name: Apply SQL schema file
      community.postgresql.postgresql_script:
        db: "{{ event_catalogue_db_name }}"
        path: /var/tmp/schema.sql
        login_password: "{{ psql_password }}"



- name: Enable replication on Event Catalogue backup host
  hosts: event_catalogue_backup
  become: yes

  tasks:
    - name: Stop postgresql service
      service:
        name: postgresql
        state: stopped
    
    - name: Clean data directory, leaving the directory itself
      shell: /bin/rm -rf /var/lib/pgsql/data/*

    - name: Create .pgpass file for pg_basebackup
      become_user: postgres
      copy:
        dest: ~/.pgpass
        mode: "700"
        content: |
           *:*:*:postgres:example

    - name: Enable replication / TODO
      become_user: postgres
      shell: "pg_basebackup -h 10.254.0.202 -p 5432 -U postgres -D /var/lib/pgsql/data/ -Fp -Xs -R"

    - name: Start postgresql service
      service:
        name: postgresql
        state: started


