- name: Deploy keepalived
  hosts: vrrp
  become: yes

  tasks:

  - name: Allow to bind on VIP even if not VRRP master
    blockinfile:
      dest: /etc/sysctl.conf 
      block: |
        net.ipv4.ip_nonlocal_bind=1 

  - name: Apply sysctl settings
    shell: sudo sysctl -p
  
  # sudo dnf update -- is it needed?

  - name: Install keepalived
    dnf: "name={{ item }} state=present"
    with_items:
      - keepalived

  - name: Set keepalived configuration
    copy:
      dest: /etc/keepalived/keepalived.conf
      content: |
        global_defs {
          router_id LVS_DEVEL
          vrrp_skip_check_adv_addr
          #vrrp_strict               # commenting this out - breaks stuff!
          vrrp_garp_interval 0
          vrrp_gna_interval 0
        }
        vrrp_instance VRRP_1 {
          state MASTER
          interface "{{ vrrp_interface }}"
          virtual_router_id 10
          priority "{{ vrrp_priority }}"
          advert_int 1
          authentication {
              auth_type PASS
              auth_pass ems-vvrp-p@ssw0rd
          }
          virtual_ipaddress {
              "{{ vrrp_ip_mask }}"
          }
        }

  - name: Start keepalived service
    service:
      name: keepalived
      state: started
      enabled: yes
